### ISSUE TITLE
colorscheme xcodedarkhc is not the same as the template

### ISSUE THREAD

**Issue by geordo** [lunacookies/vim-colors-xcode#34]
I use `colorscheme xcodedarkhc` but its color is not the same as the template
![](https://i.ibb.co/Mcf7bmH/Screenshot-2023-08-21-152929.png)

**Comment by lunacookies** [comment]
To get an appearance closer to Xcode, add `set termguicolors` to your configuration and install a plugin for C++ highlighting.
